### ISSUE TITLE
Reusing URIs

### ISSUE THREAD

**Issue by brechtvdv** [smart-data-models/dataModel.CPSV-AP#1]
In the context.jsonld file CPSV-AP terms refer to smart data models URIs, for example:
```
"hasCompetentAuthority": "https://smartdatamodels.org/dataModel.CPSV-AP/hasCompetentAuthority",
```

While in CPSV-AP, following URI is used: `http://data.europa.eu/m8g/hasCompetentAuthority`

Why not reuse the URIs?

**Comment by albertoabellagarcia** [comment]
On the contrary, we support that http://data.europa.eu/m8g/hasCompetentAuthority should be the one to be used because we do not want SDM URIs to be used. They are there only in case there were no other alternatives (and they are generated automatically).
We have a service to map every data model at SDM with external ontologies [https://smartdatamodels.org/index.php/generate-acontext-based-on-external-ontologies-iris/](https://smartdatamodels.org/index.php/generate-acontext-based-on-external-ontologies-iris/). What it is true is that we do not have the map file for doing it in this precise case.
You can see what is available here [https://github.com/smart-data-models/data-models/tree/master/context/ontologies_files](https://github.com/smart-data-models/data-models/tree/master/context/ontologies_files) 
Yuo are completely right we should have this mapping. This is pending.

**Comment by albertoabellagarcia** [comment]
Now it is available the file for the mapping. 
Available [here](https://github.com/smart-data-models/data-models/blob/master/context/ontologies_files/cpsv-ap.json)
